# Generated by Django 4.1.7 on 2023-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltocms', '0002_alter_totalenergy_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energycounter',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='energycounter',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='energycounter',
            name='ville',
        ),
        migrations.AddField(
            model_name='energycounter',
            name='consumation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='energycounter',
            name='energie_type',
            field=models.CharField(choices=[('elec', 'elec'), ('gaz', 'gaz')], default='elec', max_length=50),
        ),
        migrations.AlterField(
            model_name='energycounter',
            name='numero',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
