# Generated by Django 4.1.7 on 2023-04-06 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voltocms', '0003_remove_energycounter_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyhistory',
            name='compteur',
        ),
        migrations.AddField(
            model_name='energyhistory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='voltocms.company'),
            preserve_default=False,
        ),
    ]
